#!/usr/bin/env python3
# fuzzuf-cc
# Copyright (C) 2023 Ricerca Security
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
from fuzzuf_cc.instrumentor import Instrumentor
from fuzzuf_cc.feature.bb_id_assigner import BBIDAssignerFactory
from fuzzuf_cc.feature.bitmapfeedback import BitMapFeedbackFactory
from fuzzuf_cc.feature.forkserver import ForkServerFactory
from fuzzuf_cc.binary import CLANGpp

cc = Instrumentor("fuzzuf-afl-c++", version="0.2.0", author="Ricerca Security", base_cc=CLANGpp)

cc.add_feature(BBIDAssignerFactory())
cc.add_feature(BitMapFeedbackFactory())
cc.add_feature(ForkServerFactory())

cc.instrument()
